{% set name = "apache-airflow-providers-influxdb" %}
{% set version = "2.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_influxdb-{{ version }}.tar.gz
  sha256: 498ed9e73219f46ccbf254a2d1751544bccc98772c846393f098e0457a679491

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8
    - apache-airflow >=2.8.0
    - influxdb-client >=1.19.0
    - requests >=2.27.0,<3

test:
  imports:
    - airflow.providers.influxdb
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-influxdb for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/influxdb/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-influxdb/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
